"""
autopatch/orchestrator.py
--------------------------
LangGraph StateGraph that defines the full episode loop:

  reset → plan → read_file → code → critic
                                      ↓ approved OR retries exhausted
                                    patch → (loop back to read_file OR submit)
                                      ↓ rejected AND retries left
                                  retry_increment → code  (loop)

  submit → END

Day 1: Planner + Coder
Day 2: + Critic, retry loop, Memory (store_pattern, store_trajectory, retrieve_pattern)
Day 3: + Evolver (prompt evolution every 5 episodes), server.py
Day 5: + GitHub PR opener (fires only when final_score == 1.0)

All HTTP calls to the environment use httpx with a 30-second timeout.
ENV_URL is read at call-time so run.py can set os.environ before import.
"""

import logging
import os
from typing import List, Optional, TypedDict

import httpx
from langgraph.graph import END, StateGraph

from autopatch.agents import coder, critic, evolver, memory, planner

logger = logging.getLogger(__name__)

_MAX_RETRIES = 2  # max critic rejections per task (PRD §3.3: 1 + 2 retries = 3 total coder calls)


def _env_url() -> str:
    return os.getenv("ENV_URL", "http://localhost:7860")


# ---------------------------------------------------------------------------
# Episode state schema
# ---------------------------------------------------------------------------

class EpisodeState(TypedDict):
    run_id: str
    episode: int
    observation: dict           # latest CodeObservation from the environment
    plan: list                  # list of fix tasks from Planner
    current_task_index: int     # which task we're currently working on
    current_patch: dict         # patch dict generated by Coder; has '_review' key after Critic
    original_file: str          # file content read before patching
    rewards: list               # all rewards received this episode
    done: bool                  # True when environment is done or plan exhausted
    retry_count: int            # Critic rejections for the current task (resets per task)
    applied_patches: list       # [{path, content}] for every patch that earned reward > 0
    github_context: dict        # optional: {repo, issue_number, base_branch} for PR opener


# ---------------------------------------------------------------------------
# HTTP helpers
# ---------------------------------------------------------------------------

def _step(action: dict) -> tuple:
    """POST /step → (observation_dict, reward, done)."""
    with httpx.Client(timeout=30.0) as client:
        resp = client.post(f"{_env_url()}/step", json=action)
        resp.raise_for_status()
    data = resp.json()
    return data["observation"], data["reward"], data["done"]


def _reset(task_id: Optional[str] = None) -> dict:
    """POST /reset → raw observation dict."""
    payload = {"task_id": task_id} if task_id else {}
    with httpx.Client(timeout=30.0) as client:
        resp = client.post(f"{_env_url()}/reset", json=payload)
        resp.raise_for_status()
    return resp.json()


def _log(run_id: str, line: str) -> None:
    """Store a log line and echo to Python logger."""
    logger.info(line)
    memory.store_log(run_id, line)


# ---------------------------------------------------------------------------
# Graph nodes
# ---------------------------------------------------------------------------

def node_reset(state: EpisodeState) -> dict:
    """
    POST /reset then POST /step run_tests to capture initial pytest output.
    The observation passed to the Planner always contains pytest output.
    """
    run_id = state["run_id"]
    ep = state["episode"]
    _log(run_id, f"[RESET] episode={ep} run_id={run_id}")

    _reset()
    obs, _, _ = _step({"action_type": "run_tests"})
    _log(run_id, f"[RESET] initial pytest done task_id={obs.get('task_id')}")

    return {
        "observation": obs,
        "plan": [],
        "current_task_index": 0,
        "current_patch": {},
        "original_file": "",
        "rewards": [],
        "done": False,
        "retry_count": 0,
        "applied_patches": [],
    }


def node_plan(state: EpisodeState) -> dict:
    """Call the Planner to produce the ordered fix plan."""
    run_id = state["run_id"]
    try:
        fix_plan = planner.plan(state["observation"])
        if not fix_plan:
            _log(run_id, "[PLAN] Empty plan — submitting immediately with score 0")
            return {"plan": [], "done": True}
        files = [t.get("file") for t in fix_plan]
        _log(run_id, f"[PLAN] {len(fix_plan)} task(s): {files}")
        return {"plan": fix_plan}
    except Exception as exc:
        _log(run_id, f"[PLAN] Exception: {exc}")
        return {"plan": [], "done": True}


def node_read_file(state: EpisodeState) -> dict:
    """Read the current task's file so the Coder has its full content."""
    run_id = state["run_id"]
    idx = state["current_task_index"]

    if idx >= len(state["plan"]):
        return {"done": True}

    task = state["plan"][idx]
    file_path = task.get("file", "")
    _log(run_id, f"[READ] file={file_path} task={idx + 1}/{len(state['plan'])}")

    obs, _, _ = _step({"action_type": "read_file", "path": file_path})
    return {
        "original_file": obs.get("action_result", ""),
        "observation": obs,
        "retry_count": 0,   # reset per new task
        "current_patch": {},
    }


def node_code(state: EpisodeState) -> dict:
    """
    Generate a patch for the current task.
    On retry (retry_count > 0), passes Critic feedback back to the Coder.
    """
    run_id = state["run_id"]
    idx = state["current_task_index"]
    task = state["plan"][idx]
    bug_type = task.get("bug_type", "logic_error")

    memory_hint = memory.retrieve_pattern(bug_type)
    if memory_hint:
        _log(run_id, f"[MEMORY] Hint retrieved for bug_type={bug_type}")

    is_retry = state["retry_count"] > 0
    _log(
        run_id,
        f"[CODE] file={task.get('file')} bug_type={bug_type} "
        f"retry={state['retry_count']}/{_MAX_RETRIES}",
    )

    try:
        if is_retry:
            review = state["current_patch"].get("_review", {})
            feedback = review.get("feedback", "")
            patch = coder.code_with_retry(
                file_content=state["original_file"],
                task=task,
                memory_hint=memory_hint,
                critic_feedback=feedback,
            )
        else:
            patch = coder.code(
                file_content=state["original_file"],
                task=task,
                memory_hint=memory_hint,
            )
        _log(run_id, f"[CODE] Patch ready for {patch.get('target_file')}")
        return {"current_patch": patch}
    except Exception as exc:
        _log(run_id, f"[CODE] Exception: {exc} — terminating episode")
        return {"done": True}


def node_critic(state: EpisodeState) -> dict:
    """
    Review the proposed patch.
    Attaches the review dict to current_patch under '_review'.
    Logs a warning if confidence < 0.5 with approved=True.
    """
    run_id = state["run_id"]
    idx = state["current_task_index"]
    task = state["plan"][idx]
    bug_type = task.get("bug_type", "logic_error")

    review = critic.critique(
        original=state["original_file"],
        patch=state["current_patch"],
        bug_type=bug_type,
    )

    approved = review.get("approved", False)
    confidence = review.get("confidence", 0.0)
    feedback = review.get("feedback", "")

    if approved and confidence < 0.5:
        _log(run_id, f"[CRITIC WARNING] Low confidence ({confidence:.2f}) on approval for {bug_type}")
    elif approved:
        _log(run_id, f"[CRITIC] Approved confidence={confidence:.2f} for {task.get('file')}")
    else:
        _log(run_id, f"[CRITIC] Rejected retry={state['retry_count']}/{_MAX_RETRIES}: {feedback[:120]}")

    updated_patch = {**state["current_patch"], "_review": review}
    return {"current_patch": updated_patch}


def node_retry_increment(state: EpisodeState) -> dict:
    """
    Increment retry_count before sending the Coder back to try again.
    Exists as a dedicated node so the counter update is explicit and auditable.
    """
    new_count = state["retry_count"] + 1
    memory.store_log(
        state["run_id"],
        f"[CRITIC] retry_count → {new_count} for task {state['current_task_index'] + 1}",
    )
    return {"retry_count": new_count}


def node_patch(state: EpisodeState) -> dict:
    """Apply the patch to the environment via POST /step patch_file."""
    run_id = state["run_id"]
    patch = state["current_patch"]
    target = patch.get("target_file", "")
    _log(run_id, f"[STEP] patch_file target={target}")

    action = {
        "action_type": "patch_file",
        "target_file": target,
        "new_content": patch.get("new_content", ""),
    }
    obs, reward, done = _step(action)
    rewards = state["rewards"] + [reward]
    _log(run_id, f"[STEP] patch_file reward={reward:.3f} done={done}")

    # Store successful patterns immediately (PRD §3.6 node_patch)
    applied = list(state.get("applied_patches", []))
    if reward > 0:
        idx = state["current_task_index"]
        task = state["plan"][idx]
        memory.store_pattern(
            bug_type=task.get("bug_type", "logic_error"),
            patch_content=patch.get("new_content", ""),
            reward=reward,
        )
        _log(run_id, f"[MEMORY] Pattern stored bug_type={task.get('bug_type')} reward={reward:.3f}")
        # Accumulate for potential GitHub PR (v2)
        applied.append({
            "path":    patch.get("target_file", ""),
            "content": patch.get("new_content", ""),
        })

    return {
        "observation": obs,
        "rewards": rewards,
        "done": done,
        "current_task_index": state["current_task_index"] + 1,
        "applied_patches": applied,
    }


def node_submit(state: EpisodeState) -> dict:
    """Submit review, store trajectory, trigger Evolver (Day 3+)."""
    run_id = state["run_id"]
    rewards = state["rewards"]
    score = max(rewards) if rewards else 0.0
    n_patched = state["current_task_index"]

    summary = (
        f"AutoPatch applied {n_patched} patch(es). "
        f"Bug types: {', '.join(t.get('bug_type','') for t in state['plan'][:n_patched])}. "
        f"Score: {score:.2f}"
    )
    _log(run_id, f"[END] submitting n_patched={n_patched} score={score:.3f}")

    obs, reward, done = _step({"action_type": "submit_review", "summary": summary})
    final_rewards = rewards + [reward]
    final_score = max(final_rewards)
    _log(run_id, f"[END] terminal_reward={reward:.3f} final_score={final_score:.3f}")

    # Store trajectory for Evolver analysis (PRD §3.6 node_submit)
    memory.store_trajectory(
        run_id=run_id,
        episode=state["episode"],
        rewards=final_rewards,
        score=final_score,
    )

    # Evolver: analyse trajectories and improve Coder prompt every 5 episodes
    evolver.maybe_evolve(run_id=run_id, episode_number=state["episode"])

    # GitHub PR opener — v2 feature, fires only on perfect score (guard enforced here)
    gh_ctx = state.get("github_context") or {}
    if final_score >= 1.0 and gh_ctx.get("repo") and gh_ctx.get("issue_number"):
        _open_github_pr(state, run_id, final_rewards, final_score)

    return {"observation": obs, "rewards": final_rewards, "done": True}


def _open_github_pr(
    state: "EpisodeState",
    run_id: str,
    rewards: list,
    final_score: float,
) -> None:
    """
    Open a GitHub PR for a perfect episode (score == 1.0).
    Guard is enforced by the caller — never called with score < 1.0.
    """
    try:
        from autopatch.github.pr_opener import open_pr

        gh_ctx      = state.get("github_context", {})
        repo        = gh_ctx.get("repo", "")
        issue_num   = gh_ctx.get("issue_number")
        base_branch = gh_ctx.get("base_branch", "main")

        _log(run_id, f"[GITHUB] Opening PR on {repo} for issue #{issue_num}")

        pr_url = open_pr(
            repo=repo,
            issue_number=issue_num,
            patched_files=state.get("applied_patches", []),
            final_score=final_score,
            rewards=rewards,
            base_branch=base_branch,
        )
        _log(run_id, f"[GITHUB] PR opened: {pr_url}")

    except ImportError:
        _log(run_id, "[GITHUB] PyGithub not installed — skipping PR (pip install PyGithub)")
    except Exception as exc:
        # Never crash the episode over a PR failure
        _log(run_id, f"[GITHUB] PR open failed: {exc}")


# ---------------------------------------------------------------------------
# Routing functions
# ---------------------------------------------------------------------------

def _route_after_plan(state: EpisodeState) -> str:
    return "submit" if state.get("done") else "read_file"


def _route_after_code(state: EpisodeState) -> str:
    return "submit" if state.get("done") else "critic"


def _route_after_critic(state: EpisodeState) -> str:
    """
    approved=True OR retry_count >= _MAX_RETRIES  → patch
    approved=False AND retry_count < _MAX_RETRIES → retry_increment (then code)
    """
    review = state["current_patch"].get("_review", {})
    approved = review.get("approved", True)
    retry_count = state["retry_count"]

    if approved or retry_count >= _MAX_RETRIES:
        return "patch"
    return "retry_increment"


def _route_after_patch(state: EpisodeState) -> str:
    if state.get("done"):
        return "submit"
    if state["current_task_index"] >= len(state["plan"]):
        return "submit"
    return "read_file"


# ---------------------------------------------------------------------------
# Graph construction
# ---------------------------------------------------------------------------

def _build_graph():
    graph = StateGraph(EpisodeState)

    graph.add_node("reset", node_reset)
    graph.add_node("plan", node_plan)
    graph.add_node("read_file", node_read_file)
    graph.add_node("code", node_code)
    graph.add_node("critic", node_critic)
    graph.add_node("retry_increment", node_retry_increment)
    graph.add_node("patch", node_patch)
    graph.add_node("submit", node_submit)

    graph.set_entry_point("reset")
    graph.add_edge("reset", "plan")

    graph.add_conditional_edges(
        "plan",
        _route_after_plan,
        {"submit": "submit", "read_file": "read_file"},
    )

    graph.add_edge("read_file", "code")

    graph.add_conditional_edges(
        "code",
        _route_after_code,
        {"submit": "submit", "critic": "critic"},
    )

    graph.add_conditional_edges(
        "critic",
        _route_after_critic,
        {"patch": "patch", "retry_increment": "retry_increment"},
    )

    # retry_increment loops back to code
    graph.add_edge("retry_increment", "code")

    graph.add_conditional_edges(
        "patch",
        _route_after_patch,
        {"submit": "submit", "read_file": "read_file"},
    )

    graph.add_edge("submit", END)

    return graph.compile()


_graph = None


def _get_graph():
    global _graph
    if _graph is None:
        _graph = _build_graph()
    return _graph


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def run_episode(
    run_id: str,
    episode: int,
    github_context: Optional[dict] = None,
) -> float:
    """
    Run one full episode and return the final score (max reward across all steps).

    Parameters
    ----------
    run_id : str
        Unique identifier for this run (used by Memory for all storage ops).
    episode : int
        Episode number within the run (used by Evolver to decide when to evolve).
    github_context : dict, optional
        v2 GitHub integration context. When provided and final_score == 1.0,
        automatically opens a PR.
        Shape: {repo: "owner/repo", issue_number: int, base_branch: "main"}

    Returns
    -------
    float
        Final score for this episode.
    """
    initial_state: EpisodeState = {
        "run_id": run_id,
        "episode": episode,
        "observation": {},
        "plan": [],
        "current_task_index": 0,
        "current_patch": {},
        "original_file": "",
        "rewards": [],
        "done": False,
        "retry_count": 0,
        "applied_patches": [],
        "github_context": github_context or {},
    }

    final_state = _get_graph().invoke(initial_state)
    rewards = final_state.get("rewards", [])
    return max(rewards) if rewards else 0.0
